### ISSUE TITLE
Confused about REPS weighted NLL

### ISSUE THREAD

**Issue by sebimarkgraf** [sebascuri/rllib#1]
Hey, 
I am currently working on a university project about "Logistic Q-Learning" and there this repository is mentioned as a reference implementation.

As one of my steps consists of implementing "REPS", I compared my implementation with yours and got confused by your implementation of the weighted negative loglikelihood.

As far as I understand, the weighted NLL should optimize the following equation as mentioned in your documentation of the REPS class:
<img src="http://latex.codecogs.com/svg.latex?&space;\pi(a|x)&space;\propto&space;d_0(x,&space;a)&space;\exp^{\delta(x,&space;a)&space;/&space;\eta}" title="http://latex.codecogs.com/svg.latex? \pi(a|x) \propto d_0(x, a) \exp^{\delta(x, a) / \eta}" />

But the code in the reps implementation does not use the exponential on the weights (reps.py):
``` python
def _policy_weighted_nll(self, state, action, weights):
        """Return weighted policy negative log-likelihood."""
        pi = tensor_to_distribution(self.policy(state), **self.policy.dist_params)
        _, action_log_p = get_entropy_and_log_p(pi, action, self.policy.action_scale)
        weighted_log_p = weights.detach() * action_log_p

        # Clamping is crucial for stability so that it does not converge to a delta.
        log_likelihood = torch.mean(weighted_log_p.clamp_max(1e-3))
        return -log_likelihood
```

If I am not mistaken this could lead to problems when the weights are positive and negative, as this could change the sign of the loglikelihoods.

Would you mind explaining to me how this works?

**Comment by sebascuri** [comment]
Hi, Sebi, sorry for the delay, for some reason I didn't receive the notification. 

Ehm, I think that the point is that you try to fit a parametric policy to the RHS term. Then you try and fit the log-likelihood given by log exp(td/eta) which is just td / eta. 

For Logistic Q-Learning you can also look into this repo https://github.com/sebascuri/qreps.

**Comment by sebimarkgraf** [comment]
Thanks for the link to the QREPS implementation!

I certainly see how log(exp(td/eta)) can be simplified to td / eta.
But, as far as I understand, we calculate the loglik of the whole RHS term. 
Then, this should then be calculated as 
``` python
weighted_log_p = weights.detach() + action_log_p
```
Did I miss anything?

**Comment by sebascuri** [comment]
So I think it's different. The idea is to minimize the kl divergence between d_0e^{td/eta} and your parametric model. 

I think it is well explained [here] (https://www.jmlr.org/papers/volume17/15-188/15-188.pdf) and [here](http://eprints.lincoln.ac.uk/id/eprint/28029/1/PolicySearchReview.pdf)

However, if I did something wrong I'd be happy to fix it.

**Comment by sebimarkgraf** [comment]
I have read the mentioned sources and maybe I can write more about my thought process:
In the [first source](https://www.jmlr.org/papers/volume17/15-188/15-188.pdf) they formulate the update process in the sample REPS case from the KL-Divergence between following policies explicitly as equation (7)
![image](https://user-images.githubusercontent.com/24530526/111505398-de2fc600-8748-11eb-9826-12bd91cbb7c7.png)

I understand how they derived that formulation and I am stuck in how to transform it into the implemented form. 
If I understand the python code correctly, it implements:
<img src="http://latex.codecogs.com/svg.latex?w_i&space;=&space;\left(\frac{r(s_i,&space;a_i)&space;\mathbb{E}[\theta^T(s')|s_i,&space;a_i]&space;-&space;\theta^T&space;\phi(s')}{\eta}&space;\right)" title="http://latex.codecogs.com/svg.latex?w_i = \left(\frac{r(s_i, a_i) \mathbb{E}[\theta^T(s')|s_i, a_i] - \theta^T \phi(s')}{\eta} \right)" />

Let's suppose the bellman error for \(s_i, a_i\) is negative. In that case, the formulation of (7) will still be positive but small due to the exponential, but the implemented version will be negative. When multiplying the negative weight in the NLL, the sample that would be normally weighted small in (7) is now weighted strongly due to the change in the sign.

**Comment by sebascuri** [comment]
Oh I think you might be right! Thank you for catching that :) 

This might be annoying for you, but what happens if you change line 98 of https://github.com/sebascuri/rllib/blob/master/rllib/algorithms/reps.py  to: 
        nll = self._policy_weighted_nll(state, action, torch.exp(weights))

I will check it out see if it works too.

**Comment by sebimarkgraf** [comment]
To make it easier to see the influence, I have run the example for REPS in your repository.
This is the return without the change:
![image](https://user-images.githubusercontent.com/24530526/111600677-f0097b80-87d1-11eb-9a20-8c04651843f9.png)
And here is the return with the change:
![image](https://user-images.githubusercontent.com/24530526/111600766-031c4b80-87d2-11eb-98a7-c1978d2b0d9f.png)
I would go ahead and create a PR with the change if it is okay for you.

**Comment by sebascuri** [comment]
oh wow! please do, I was also trying things on the half cheetah to see if it works but couldn't manage yet. Did you change something more than that function?

**Comment by sebascuri** [comment]
Hi @sebimarkgraf thanks for the pull request. I did some refactoring and as well added a clamping on the torch.exp to be sure that it was still stable even with varying \eta. Maybe the clamping is not the best either? What do you think would happen if we do torch.exp(td - td.max())? In a full-batch setting this shouldn't be an issue, in an SGD I'm not sure. 

I don't have much intuition on how to set \eta for REPS, nor if regularizing or making a trust-region constraint is empirically better, so if you have any insights I'd be happy to learn.

**Comment by sebimarkgraf** [comment]
Unfortunately, my knowledge about setting \eta is limited as well.
My parameter search was not really conclusive but I had a good experience with quite aggressive values for \eta (5.0).
REPS even converged in around 4 iterations to the optimal cartpole policy.

I tried optimizing the continuous cartpole from dm_comtrol, but so far no success.
